Travis: publishing only tagged commits.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -21,30 +21,35 @@ env:
 after_success:
   - |
       if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
-        echo "Waiting for other builds..."
-        curl -s -o travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
-        python travis_after_all.py
-        export $(cat .to_export_back)
-        if [ "$BUILD_LEADER" = "YES" ]; then
-          if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
-            git config --global user.name "Travis-CI"
-            git config --global user.email $EMAIL
-            echo "Cloning dist..."
-            git clone https://$GH_TOKEN@github.com/jDataView/dist2.git ~/dist &>-
-            echo "Copying generated files into dist..."
-            cp dist/browser/{*.js,*.js.map} ~/dist/
-            echo "Committing..."
-            pushd ~/dist > /dev/null
-            git add .
-            git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
-            echo "Publishing..."
-            git push origin gh-pages &>-
-            popd
-            echo "Published browser dist."
-            grunt npm-publish
-          else
-            echo "Some of builds were failed."
+        git describe --exact-match HEAD 
+        if [ $? -eq 0 ]; then
+          echo "Checking other builds..."
+          curl -s -o travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
+          python travis_after_all.py
+          export $(cat .to_export_back)
+          if [ "$BUILD_LEADER" = "YES" ]; then
+            if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
+              git config --global user.name "Travis-CI"
+              git config --global user.email $EMAIL
+              echo "Cloning dist..."
+              git clone https://$GH_TOKEN@github.com/jDataView/dist2.git ~/dist &>-
+              echo "Copying generated files into dist..."
+              cp dist/browser/{*.js,*.js.map} ~/dist/
+              echo "Committing..."
+              pushd ~/dist > /dev/null
+              git add .
+              git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
+              echo "Publishing..."
+              git push origin gh-pages &>-
+              popd
+              echo "Published browser dist."
+              grunt npm-publish
+            else
+              echo "Some of builds were failed."
+            fi
           fi
+        else
+          echo "No tags found, not publishing."
         fi
       else
         echo "Pull request detected, not publishing."
